### PR TITLE
convert to Minilla

### PR DESCRIPTION
**Pull request by Grinnz**
If so inclined here is a conversion to use Minilla for releasing. See https://metacpan.org/pod/Minilla and https://metacpan.org/pod/Minilla::Tutorial. Some notes:

* I added no_github_issues=true in the minil.toml since github issues are not currently marked in metadata, but you can remove this line if you want to use github issues instead of RT.
* You can use `minil test` to test the dist, `minil release` to release it to CPAN. `minil test --release` will additionally include release tests like are run during releasing.
* Removed t/pod.t as Minilla includes this as a release test.
* Changed `use 5.14.0` to `use 5.014` to make Test::MinimumVersion::Fast happy.
* `minil release --trial` can be used to make a trial release without using underscores in the version, as discussed in #24.
* {{$NEXT}} is a template tag for Changes that will be updated with the version and date of the release when releasing.
* Minilla generates README.md from the main module pod so it replaces the one that's in the repo already. Don't think there's a way to disable it.

If you want the ability of more customization (like how the readme is generated, or really anything) I can do a switch to Dist::Milla instead, which is similar in usage but as it is a Dist::Zilla bundle it requires installing all of that -- but you get access to any Dist::Zilla plugin customization you want to do.

### CODE REVIEW

**Comment by TJC** [comment]
@nohuhu -- this looks pretty good to me. Would merging it now cause you any grief in your current work?

**Comment by nohuhu** [comment]
Wow, this is über cool. Thanks a bunch @Grinnz!

My current branch is hitting some bumps on older Postgres versions (9.2-) so might take a bit longer than anticipated. I'll rebase on top of these changes later, no problem.

**Comment by nohuhu** [comment]
@Grinnz Sorry to resurrect this discussion but I'm having a bit of trouble with `minil test`. It re-generates README and META.json every time, replacing the master Git repo URL with my fork. Do you know a way to disable that?

**Comment by Grinnz** [comment]
Sadly I do not. That's the sort of customization you would probably need Dist::Milla to do. One workaround (which I did to generate the files correctly for this PR) is to set your branch's upstream to the main repo while testing, or alternatively, you can just checkout META.json and README before committing to revert them to the committed state.

**Comment by Grinnz** [comment]
This is where the repo metadata is extracted, it's actually the URL of the `origin` remote itself. Perhaps a PR would be accepted to make the user portion configurable when it's a github url. https://github.com/tokuhirom/Minilla/blob/6ef4c2f1ab7eafe5b143b11c0e0fb7e330aa06c9/lib/Minilla/Project.pm#L488

**Comment by nohuhu** [comment]
This matches my observations: I have two remotes for this repo, `origin` pointing to my fork and `upstream` pointing to TJC repo, and the meta gets replaced with `origin` url.

I'll look into submitting a PR to Minilla, thanks.

**Pull request merged**
